spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: exemplo-service
          uri: lb://exelpo-service
          predicates:
            - Path=/exemplo/**
          filters:
            - RewritePath=/exmplo/(?<path>.*), /$\{path}

server:
  port: 8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  file: logs/gateway-service.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: "1.8"