server:
    port: 8761
spring:
  application:
    name: discovery-service


eureka:
  datacenter: MixedSalad
  instance:
    hostname: discovery-service
    client:
      registerWithEureka: true
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000